spring:
  application:
    name: gateway-service

server:
  port: 5000

 
zuul:
  routes:
    order-service:
      path: /order/**
      service-id: order-service

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka      

management:
  server:
    port: 5080
  endpoint:
    beans:
      enabled: true
    health:
      show-details: ALWAYS
    env:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'   