spring:
  application:
    name: square-service-ui

server:
  port: 8080
  
info:
  name: square-service-ui

eureka:  client:
    enabled: true    service-url:      defeaultZone: http://localhost:8761/eureka
 
square:
  #base-url: http://localhost:7001/squareservice
    #Diable to route via gateway   
  base-url: http://localhost:5000/square-service/squareservice
  
management:
  server:
    port: 9000
  endpoint:
    beans:
      enabled: true
    health:
      show-details: ALWAYS
    env:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*' 