spring:
  application:
    name: ms-config-server
  cloud: 
    config:
      server:
        git: # URI of GIT repo containing properties
          uri: https://github.com/akhiljn03/SpringBoot
          searchPaths: Training/Microservices/Ordering/Configuration
          # path to properties from root of repo
           
server:
  port: 8011

eureka:
  client:
    enabled: true
    service-url:
      defeaultZone: http://localhost:8761/eureka
      
management:
  server:
    port: 9011
  endpoint:
    beans:
      enabled: true
    health:
      show-details: ALWAYS
    env:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*' 
        
#Actuator properties for /info Implementation
info:
  app:
    name: Config Server
    description: Config Server    
