spring:
  application:
    name: gateway-service

server:
  port: 5000

eureka:
  client:
    enabled: true
    service-url:
      defeaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    square-service:
      path: /squareservice/**
      service-id: square-service
    account-service:
      path: /account/**
      service-id: account-service

management:
  server:
    port: 9003
  endpoint:
    beans:
      enabled: true
    health:
      show-details: ALWAYS
    env:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*' 