server:
  port: 8761 #Default Port for Eureka
  
spring:
  application:
    name: ms-discovery-server
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false  
    
     #We are telling the built-in Eureka Client not to register with ‘itself' 
     #because our application should be acting as a server
