server:
  port: 8010
  
spring:
  application:
    name: ms-ordering-service
    
eureka:
  client:
    enabled: true
    service-url:
      defeaultZone: http://localhost:8761/eureka
      
      
management:
  server:
    port: 9010
  endpoint:
    beans:
      enabled: true
    health:
      show-details: ALWAYS
    env:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*' 
        
#Actuator properties for /info Implementation
info:
  app:
    name: Ordering Service
    description: Ordering Service for Order UI