spring:
  application:
    name: movie-omdb-api

  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616

server:
  port: 7002    

omdb: 
  base:
    url: http://www.omdbapi.com/?i=tt3896198&apikey=52d1c7f

movie:
  input: movie.input
  output: movie.output  
