spring:
  application:
    name: square-service

server:
  port: 7001    

eureka:
  client:
      enabled: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka

management:
  server:
    port: 9001
  endpoint:
    beans:
      enabled: true
    health:
      show-details: ALWAYS
    env:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'   