server:
  port: 4000
  
spring:
  application:
    name: training-gateway-server
    
eureka:
  client:
    enabled: true
    service-url:
      defeaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    weather-service:
      path: /weather/**
      service-id: weather-service
  
